#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Agent Generator - Creates custom sub-agents for specialized workflow tasks

This script generates sub-agent definition files when workflows require
specialized capabilities not covered by existing agents.
"""

import os
import yaml
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime


class AgentGenerator:
    """Generate sub-agent files for specialized workflow tasks"""

    def __init__(self, output_dir: str = "~/.claude/agents/workflows"):
        self.output_dir = Path(output_dir).expanduser()
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def should_create_agent(self, workflow_spec: Dict[str, Any]) -> bool:
        """
        Determine if a custom agent should be created

        Criteria for creating a new agent:
        1. High complexity (complex/high)
        2. Specialized domain not covered by existing personas
        3. Reusable pattern that will be used across multiple workflows
        4. Unique combination of capabilities
        """
        complexity = workflow_spec.get('complexity', 'standard')
        domain = workflow_spec.get('domain', '')
        reusable = workflow_spec.get('reusable', False)

        # High complexity or explicitly marked as reusable
        if complexity in ['complex', 'high'] or reusable:
            return True

        # Specialized domains
        specialized_domains = [
            'machine-learning',
            'data-pipeline',
            'infrastructure',
            'distributed-systems',
            'security-audit'
        ]

        if domain in specialized_domains:
            return True

        return False

    def generate(self, workflow_spec: Dict[str, Any], agent_spec: Dict[str, Any]) -> Path:
        """
        Generate a custom sub-agent file

        Args:
            workflow_spec: Original workflow specification
            agent_spec: Specific agent configuration:
                - name: Agent name
                - description: Agent description
                - category: Agent category
                - triggers: When to activate
                - focus_areas: List of focus areas
                - key_actions: List of key actions
                - outputs: Expected outputs
                - boundaries: What agent will/won't do

        Returns:
            Path to generated agent file
        """
        name = agent_spec['name']
        agent_content = self._build_agent_content(agent_spec, workflow_spec)

        output_file = self.output_dir / f"{name}.md"
        output_file.write_text(agent_content)

        print(f"✅ Generated agent: {output_file}")
        return output_file

    def _build_agent_content(self, agent_spec: Dict[str, Any],
                            workflow_spec: Dict[str, Any]) -> str:
        """Build the complete markdown content for the agent"""

        # Build frontmatter
        frontmatter = self._build_frontmatter(agent_spec)

        # Build main sections
        content = f"""---
{frontmatter}---

# {agent_spec['name'].replace('-', ' ').title()}

## Triggers
{self._build_triggers(agent_spec)}

## Behavioral Mindset
{agent_spec.get('behavioral_mindset', 'Execute specialized workflow tasks with precision and efficiency.')}

## Focus Areas
{self._build_focus_areas(agent_spec)}

## Key Actions
{self._build_key_actions(agent_spec)}

## Outputs
{self._build_outputs(agent_spec)}

## Boundaries
{self._build_boundaries(agent_spec)}

---
*Generated by workflow-creator skill on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
*Parent workflow: {workflow_spec.get('name', 'unknown')}*
"""
        return content

    def _build_frontmatter(self, agent_spec: Dict[str, Any]) -> str:
        """Build YAML frontmatter for agent"""
        frontmatter_data = {
            'name': agent_spec['name'],
            'description': agent_spec['description'],
            'category': agent_spec.get('category', 'specialized'),
        }

        return yaml.dump(frontmatter_data, default_flow_style=False, sort_keys=False)

    def _build_triggers(self, agent_spec: Dict[str, Any]) -> str:
        """Build triggers section"""
        triggers = agent_spec.get('triggers', [])

        if not triggers:
            return "- Specialized workflow execution requiring domain expertise"

        trigger_text = ""
        for trigger in triggers:
            trigger_text += f"- {trigger}\n"

        return trigger_text.strip()

    def _build_focus_areas(self, agent_spec: Dict[str, Any]) -> str:
        """Build focus areas section"""
        focus_areas = agent_spec.get('focus_areas', [])

        if not focus_areas:
            return "- Specialized task execution\n- Domain-specific problem solving"

        focus_text = ""
        for area in focus_areas:
            area_name = area.get('name', '')
            area_desc = area.get('description', '')
            focus_text += f"- **{area_name}**: {area_desc}\n"

        return focus_text.strip()

    def _build_key_actions(self, agent_spec: Dict[str, Any]) -> str:
        """Build key actions section"""
        actions = agent_spec.get('key_actions', [])

        if not actions:
            return "1. Analyze requirements and constraints\n2. Execute specialized tasks systematically\n3. Validate results and handle edge cases"

        action_text = ""
        for i, action in enumerate(actions, 1):
            action_name = action.get('name', f'Action {i}')
            action_desc = action.get('description', '')
            action_text += f"{i}. **{action_name}**: {action_desc}\n"

        return action_text.strip()

    def _build_outputs(self, agent_spec: Dict[str, Any]) -> str:
        """Build outputs section"""
        outputs = agent_spec.get('outputs', [])

        if not outputs:
            return "- Executed workflow tasks with validation\n- Progress reports and status updates\n- Error handling and recovery recommendations"

        output_text = ""
        for output in outputs:
            output_name = output.get('name', '')
            output_desc = output.get('description', '')
            output_text += f"- **{output_name}**: {output_desc}\n"

        return output_text.strip()

    def _build_boundaries(self, agent_spec: Dict[str, Any]) -> str:
        """Build boundaries section"""
        will_do = agent_spec.get('will_do', [])
        wont_do = agent_spec.get('wont_do', [])

        boundary_text = "**Will:**\n"
        if will_do:
            for item in will_do:
                boundary_text += f"- {item}\n"
        else:
            boundary_text += "- Execute specialized workflow tasks with precision\n"
            boundary_text += "- Handle domain-specific requirements appropriately\n"

        boundary_text += "\n**Will Not:**\n"
        if wont_do:
            for item in wont_do:
                boundary_text += f"- {item}\n"
        else:
            boundary_text += "- Make decisions outside specialized domain\n"
            boundary_text += "- Proceed without necessary context or validation\n"

        return boundary_text.strip()


def main():
    """Test the agent generator"""

    # Example workflow spec
    workflow_spec = {
        'name': 'data-pipeline-workflow',
        'complexity': 'high',
        'domain': 'data-pipeline'
    }

    # Example agent spec
    agent_spec = {
        'name': 'data-pipeline-specialist',
        'description': 'Specialized agent for data pipeline orchestration and ETL operations',
        'category': 'data-engineering',
        'behavioral_mindset': 'Focus on data quality, pipeline reliability, and efficient transformation processing',
        'triggers': [
            'Data pipeline design and implementation requests',
            'ETL job configuration and optimization',
            'Data quality validation requirements',
            'Pipeline monitoring and error recovery scenarios'
        ],
        'focus_areas': [
            {
                'name': 'Pipeline Design',
                'description': 'Architecture and workflow design for data pipelines'
            },
            {
                'name': 'ETL Operations',
                'description': 'Extract, Transform, Load job implementation'
            },
            {
                'name': 'Data Quality',
                'description': 'Validation, cleansing, and quality assurance'
            },
            {
                'name': 'Error Handling',
                'description': 'Robust error recovery and retry mechanisms'
            }
        ],
        'key_actions': [
            {
                'name': 'Design Pipeline',
                'description': 'Create efficient data pipeline architecture with proper staging'
            },
            {
                'name': 'Implement Transformations',
                'description': 'Develop data transformation logic with validation'
            },
            {
                'name': 'Configure Scheduling',
                'description': 'Set up pipeline orchestration and scheduling'
            },
            {
                'name': 'Monitor & Optimize',
                'description': 'Track performance and optimize bottlenecks'
            }
        ],
        'outputs': [
            {
                'name': 'Pipeline Configuration',
                'description': 'Complete pipeline definition with dependencies'
            },
            {
                'name': 'ETL Scripts',
                'description': 'Transformation and loading code'
            },
            {
                'name': 'Monitoring Setup',
                'description': 'Alerting and observability configuration'
            }
        ],
        'will_do': [
            'Design scalable data pipelines with proper error handling',
            'Implement ETL operations following best practices',
            'Configure monitoring and alerting for pipeline health'
        ],
        'wont_do': [
            'Make infrastructure decisions without architectural review',
            'Implement pipelines without proper data quality validation',
            'Bypass security or compliance requirements'
        ]
    }

    generator = AgentGenerator()

    if generator.should_create_agent(workflow_spec):
        output_path = generator.generate(workflow_spec, agent_spec)
        print(f"\n🤖 Generated agent file at: {output_path}")
    else:
        print("\n⏭️  Agent creation not needed for this workflow")


if __name__ == '__main__':
    main()
