#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command Generator - Generates executable slash commands for workflows

This script takes workflow analysis data and creates a properly formatted
markdown file that can be used as a Claude Code slash command.
"""

import os
import yaml
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime


class CommandGenerator:
    """Generate slash command files from workflow specifications"""

    def __init__(self, output_dir: str = "~/.claude/commands/workflows"):
        self.output_dir = Path(output_dir).expanduser()
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, workflow_spec: Dict[str, Any]) -> Path:
        """
        Generate a complete command file from workflow specification

        Args:
            workflow_spec: Dictionary containing:
                - name: Command name
                - description: Command description with workflow graph
                - category: workflow/automation/analysis/etc
                - complexity: simple/standard/complex/high
                - mcp_servers: List of MCP servers to use
                - personas: List of expert personas
                - workflow_steps: List of workflow steps
                - metadata: Additional metadata

        Returns:
            Path to generated command file
        """
        name = workflow_spec['name']
        command_content = self._build_command_content(workflow_spec)

        output_file = self.output_dir / f"{name}.md"
        output_file.write_text(command_content)

        print(f"✅ Generated command: {output_file}")
        return output_file

    def _build_command_content(self, spec: Dict[str, Any]) -> str:
        """Build the complete markdown content for the command"""

        # Build frontmatter
        frontmatter = self._build_frontmatter(spec)

        # Build description with workflow graph
        description = self._build_description(spec)

        # Build behavioral instructions
        behavior = self._build_behavior_section(spec)

        # Build MCP integration section
        mcp_section = self._build_mcp_section(spec)

        # Build examples
        examples = self._build_examples_section(spec)

        # Combine all sections
        content = f"""---
{frontmatter}---

# /{spec['name']} - {spec.get('title', 'Custom Workflow')}

{description}

## Behavioral Flow

{behavior}

## MCP Integration

{mcp_section}

## Usage Examples

{examples}

## Boundaries

**Will:**
- Execute the defined workflow according to dependencies
- Handle errors and edge cases appropriately
- Coordinate multiple tools and personas as needed

**Will Not:**
- Skip critical validation steps
- Proceed if dependencies are not met
- Override explicit user constraints

---
*Generated by workflow-creator skill on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        return content

    def _build_frontmatter(self, spec: Dict[str, Any]) -> str:
        """Build YAML frontmatter"""
        frontmatter_data = {
            'name': spec['name'],
            'description': spec['description'],
            'category': spec.get('category', 'workflow'),
            'complexity': spec.get('complexity', 'standard'),
        }

        if spec.get('mcp_servers'):
            frontmatter_data['mcp-servers'] = spec['mcp_servers']

        if spec.get('personas'):
            frontmatter_data['personas'] = spec['personas']

        return yaml.dump(frontmatter_data, default_flow_style=False, sort_keys=False)

    def _build_description(self, spec: Dict[str, Any]) -> str:
        """Build description section with workflow graph"""
        workflow_graph = spec.get('workflow_graph_text', '')
        patterns = spec.get('detected_patterns', [])

        desc = f"> **Workflow Description**: {spec['description']}\n\n"

        if patterns:
            pattern_list = ', '.join([p['pattern'] for p in patterns])
            desc += f"**Detected Patterns**: {pattern_list}\n\n"

        if workflow_graph:
            desc += f"## Workflow Graph\n\n```\n{workflow_graph}\n```\n"

        return desc

    def _build_behavior_section(self, spec: Dict[str, Any]) -> str:
        """Build behavioral instructions"""
        steps = spec.get('workflow_steps', [])

        if not steps:
            return "Execute workflow according to the graph structure above."

        behavior = ""
        for i, step in enumerate(steps, 1):
            step_name = step.get('name', f'Step {i}')
            step_desc = step.get('description', '')
            step_type = step.get('type', 'sequential')

            if step_type == 'parallel':
                behavior += f"{i}. **{step_name}** (parallel execution)\n"
            elif step_type == 'conditional':
                behavior += f"{i}. **{step_name}** (conditional)\n"
            elif step_type == 'async':
                behavior += f"{i}. **{step_name}** (async, non-blocking)\n"
            else:
                behavior += f"{i}. **{step_name}**\n"

            if step_desc:
                behavior += f"   - {step_desc}\n"

            behavior += "\n"

        return behavior.strip()

    def _build_mcp_section(self, spec: Dict[str, Any]) -> str:
        """Build MCP integration section"""
        mcp_servers = spec.get('mcp_servers', [])
        mcp_rationale = spec.get('mcp_rationale', {})

        if not mcp_servers:
            return "No specialized MCP servers required for this workflow."

        mcp_section = ""
        for server in mcp_servers:
            rationale = mcp_rationale.get(server, 'Supporting workflow execution')
            mcp_section += f"- **{server} MCP**: {rationale}\n"

        return mcp_section.strip()

    def _build_examples_section(self, spec: Dict[str, Any]) -> str:
        """Build usage examples"""
        examples = spec.get('examples', [])
        name = spec['name']

        if not examples:
            # Generate default example
            return f"""```bash
/{name}

# The workflow will execute according to the defined graph structure
```"""

        examples_text = ""
        for example in examples:
            input_text = example.get('input', '')
            output_text = example.get('output', '')

            examples_text += f"### {example.get('title', 'Example')}\n\n"
            examples_text += f"```bash\n/{name}\n{input_text}\n```\n\n"

            if output_text:
                examples_text += f"**Expected behavior**:\n{output_text}\n\n"

        return examples_text.strip()


def main():
    """Test the command generator"""

    # Example workflow specification
    example_spec = {
        'name': 'example-workflow',
        'title': 'Example Multi-Step Workflow',
        'description': 'Demonstrates command generation for a complex workflow',
        'category': 'workflow',
        'complexity': 'standard',
        'mcp_servers': ['sequential', 'serena'],
        'personas': ['system-architect', 'backend-developer'],
        'detected_patterns': [
            {'pattern': 'flow', 'confidence': 0.9},
            {'pattern': 'branch', 'confidence': 0.7}
        ],
        'workflow_graph_text': '''→ Initialize [node_1]
→ Analyze Code [node_2]
  ├─ [ComplexityHigh] → Refactor [node_3]
  └─ [ComplexityOK] → Continue [node_4]
→ Run Tests [node_5]
→ Deploy [node_6]''',
        'workflow_steps': [
            {
                'name': 'Initialize',
                'description': 'Set up environment and dependencies',
                'type': 'sequential'
            },
            {
                'name': 'Analyze Code',
                'description': 'Evaluate code quality and complexity',
                'type': 'sequential'
            },
            {
                'name': 'Decision Point',
                'description': 'Decide whether refactoring is needed',
                'type': 'conditional'
            },
            {
                'name': 'Run Tests',
                'description': 'Execute test suite',
                'type': 'sequential'
            },
            {
                'name': 'Deploy',
                'description': 'Deploy to target environment',
                'type': 'sequential'
            }
        ],
        'mcp_rationale': {
            'sequential': 'Complex multi-step analysis and coordination',
            'serena': 'Code analysis and refactoring operations'
        },
        'examples': [
            {
                'title': 'Basic Usage',
                'input': '# Analyze project in current directory',
                'output': 'Workflow executes all steps according to graph'
            }
        ]
    }

    generator = CommandGenerator()
    output_path = generator.generate(example_spec)
    print(f"\n📄 Generated command file at: {output_path}")


if __name__ == '__main__':
    main()
